version: '3.7'

services:
  api:
    restart: unless-stopped
    build: .
    environment:
      - NODE_ENV=production
      - MONGO_DB_URI=mongodb+srv://root:GeAnKWlRF8qeRK7V@cluster0.muqfv5x.mongodb.net/?retryWrites=true&w=majority
      - PORT=4000
    ports:
      - 4000:4000
    # volumes:
    #   - ./api:/usr/src/app